# This workflow will run the Planemo test scripts for the tools
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: planemo-ci-tests

on: [push, pull_request]

jobs:
  run-ci-tests:
    # Use 'runs-on: ubuntu-20.04' if you need Python 3.6
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        galaxy-tool: ["trimmomatic", "pal_finder", "weeder2", "rnachipintegrator", "macs21", "motif_tools"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Virtualenv
        run: sudo apt-get install python3-virtualenv
      - name: Install Planemo
        run: python -m pip install planemo
      - name: Run test for ${{ matrix.galaxy-tool }}
        run: ./tools/${{ matrix.galaxy-tool }}/run_planemo_tests.sh
