# This workflow will run the Planemo test scripts for the tools
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: planemo-ci-tests

on: [push, pull_request]

jobs:
  setup:
    # Use 'runs-on: ubuntu-20.04' if you need Python 3.6
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Planemo
        run: python -m pip install planemo

  run-ci-tests:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        galaxy-tool: ["trimmomatic", "pal_finder", "weeder2", "rnachipintegrator", "macs21", "motif_tools"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Planemo
        run: python -m pip install planemo
      - name: Report CWD
        run: pwd
      - name: List contents of CWD
        run: ls -l
      - name: Run test for ${{ matrix.galaxy-tool }}
        run: ./tools/${{ matrix.galaxy-tool }}/run_planemo_tests.sh
