# This workflow will run the Planemo test scripts for the tools
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: planemo-ci-tests

on: [push, pull_request]

jobs:
  run-ci-tests:
    # Use 'runs-on: ubuntu-20.04' if you need Python 3.6
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Define the tools to test
        galaxy-tool: ["trimmomatic", "pal_finder", "weeder2", "rnachipintegrator", "macs21", "motif_tools"]
	# This gives the option to test against multiple Galaxy versions
	galaxy-version: ["20.05"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Virtualenv
        run: sudo apt-get install python3-virtualenv
      - name: Install Planemo
        run: python -m pip install planemo
      - name: Checkout Galaxy version ${{ matrix.galaxy-version }}
        run: "git clone https://github.com/galaxyproject/galaxy/ -b release_${{ matrix.galaxy-version }} galaxy_${{ matrix.galaxy-version }}"
      - name: Run test for ${{ matrix.galaxy-tool }}
        run: "./tools/${{ matrix.galaxy-tool }}/run_planemo_tests.sh --galaxy_root galaxy_${{ matrix.galaxy-version }}"
